config:
  target: "ws://localhost:3003"
  processor: "./load-test-functions.js"
  phases:
    # - name: "Leak test"
      # duration: 5
      # arrivalCount: 5
    - name: "Warm up"
      duration: 60
      arrivalCount: 5000
    # - name: "Ramp up"
      # duration: 60 * 5
      # arrivalRate: 316
    # - name: "Maximum"
      # duration: 20
      # arrivalRate: 33250
  ws:
    rejectUnauthorized: false
    subprotocols: json
    headers:
      Origin: "http://localhost:3000"

scenarios:
  - engine: "ws"
    flow:
      - function: "initListeners"

      - function: "generateId"
      - send:
          id: "{{ id }}"
          mock-login:
            identity: "jack@jackburgess.dev"
            password: "elect"
      # - think: 2
      # - send:
          # id: "{{ id }}"
          # "dashboard:load":
            # key: "{{ received.user.key }}"
      - think: 5
      - function: "selectParty"
      - send:
          id: "{{ id }}"
          "vote:cast":
            electionId: "5c5df895fde2504c5eaa2301"
            # electionId: "{{ received.election._id }}"
            partyId: "{{ party }}"
            key: "{{ received.user.key }}"
      - think: 60

