config:
  target: "ws://elect.salvo.sh"
  processor: "./load-test-functions.js"
  phases:
    - name: "Warm up"
      duration: 60
      arrivalRate: 74
    - name: "Ramp up"
      duration: 60
      arrivalRate: 74
      rampTo: 745
    - name: "Sustained Average"
      duration: 60
      arrivalRate: 745
    - name: "Peak Load"
      duration: 60
      arrivalRate: 1000
  ws:
    rejectUnauthorized: false
    subprotocols: json
    headers:
      Origin: "http://elect.salvo.sh"
  plugins:
    datadog:
      prefix: 'artillery.'

scenarios:
  - engine: "ws"
    flow:
      - function: "generateId"
      - send:
          id: "{{ id }}"
          mock-login:
            identity: "jack@jackburgess.dev"
            password: "elect"
      - think: 5
      - send:
          id: "{{ id }}"
          "dashboard:load":
            key: "load-test-mock-key"
      - think: 5
      - function: "selectParty"
      - send:
          id: "{{ id }}"
          "vote:cast":
            electionId: "5c5df895fde2504c5eaa2301"
            partyId: "{{ party }}"
            key: "load-test-mock-key"
      - think: 60
