config:
  target: "ws://localhost:3003"
  processor: "./load-test-functions.js"
  phases:
    # - name: "Leak test"
      # duration: 10
      # arrivalCount: 100
    - name: "Warm up"
      duration: 60
      arrivalCount: 5000
    - name: "Ramp up"
      duration: 300 # 5 minutes
      arrivalCount: 95000
    # - name: "Maximum"
      # duration: 20
      # arrivalRate: 33250
  ws:
    rejectUnauthorized: false
    subprotocols: json
    headers:
      Origin: "http://localhost:3003"

scenarios:
  - engine: "ws"
    flow:
      - function: "generateId"
      - send:
          id: "{{ id }}"
          mock-login:
            identity: "jack@jackburgess.dev"
            password: "elect"
      - think: 5
      - send:
          id: "{{ id }}"
          "dashboard:load":
            key: "load-test-mock-key"
      - think: 5
      - function: "selectParty"
      - send:
          id: "{{ id }}"
          "vote:cast":
            electionId: "5c5df895fde2504c5eaa2301"
            partyId: "{{ party }}"
            key: "load-test-mock-key"
      - think: 60

